/**
  * @brief CAUTION: do not change this file - it is autogenerated.
  */

#include "proto.h"
#include <common/xroad_aux.h>

typedef struct
{
   uint16_t block_length;
   uint16_t template_id;
   uint16_t schema_id;
   uint16_t version;
} message_header_t;

typedef struct
{
   uint16_t length;
   char data[];
} var_string_t;

typedef struct
{
   uint16_t block_length;
   uint16_t num_in_group;
} group_size_encoding_t;

typedef struct
{
   char* data;
   size_t len;
   car_logger_cback_t cback;
   size_t var_offset;
} decoder_t;

struct car_group_decoder_s
{
   void* decoder;
   uint16_t idx;
   char* data;
};

typedef struct car_group_decoder_s car_group_decoder_t;

struct car_default_decoder_s
{
   decoder_t* base;
};

// types

// groups

// messages

typedef struct
{
   int32_t id[1];
   char name[20];
} car_t;

