/**
  * @brief CAUTION: do not change this file - it is autogenerated.
  */

#include ""
#include <common/xroad_aux.h>
#include <math.h>

typedef struct
{
   uint16_t block_length;
   uint16_t template_id;
   uint16_t schema_id;
   uint16_t version;
} message_header_t;

typedef struct
{
   uint16_t block_length;
   uint16_t num_in_group;
} group_size_encoding_t;

typedef struct
{
   char* data;
   size_t len;
   car_logger_cback_t cback;
   size_t var_offset;
} decoder_t;

struct car_group_decoder_s
{
   void* decoder;
   uint16_t idx;
   char* data;
};

typedef struct car_group_decoder_s car_group_decoder_t;

struct car_default_decoder_s
{
   decoder_t* base;
};


// types

// groups

// messages

typedef struct
{
   int32_t id;
   char name[20];
} car_t;

//--------------------------------------------------------------------------------------------------------------------//
void* car_decode(char* data, size_t len, car_logger_cback_t cback)
{
   if (len < sizeof(message_header_t))
   {
      cback(car_log_level_error, "data is too short to decode");
      return NULL;
   }
   message_header_t* hdr = (message_header_t*)data;
   switch(hdr->template_id)
   {
      case car_template_car:
      {
         if (len < sizeof(message_header_t) + 24)
         {
            if (cback)
            {
               cback(car_log_level_error, "data is too short to decode");
            }
            return NULL;
         }
         car_car_decoder_t* decoder = calloc(1, sizeof(car_car_decoder_t));
         decoder->base.data = data;
         decoder->base.len = len;
         decoder->base.cback = cback;
         return decoder;
      }
      default:
      {
         if (cback)
         {
            cback(car_log_level_error, "unknown template id");
         }
         return NULL;
      }
   }
}

//--------------------------------------------------------------------------------------------------------------------//
void car_destroy_decoder(void* decoder)
{
   free(decoder);
}

//--------------------------------------------------------------------------------------------------------------------//
int32_t car_car_get_id(car_car_decoder_t* d)
{
   decoder_t* base = &d->base;
   car_t* obj = (car_t*)(base->data + base->var_offset + sizeof(message_header_t));
   return obj->id;
}

//--------------------------------------------------------------------------------------------------------------------//
xroad_str_t car_car_get_name(car_car_decoder_t* d)
{
   decoder_t* base = &d->base;
   car_t* obj = (car_t*)(base->data + base->var_offset + sizeof(message_header_t));
   return xroad_str_len(obj->name, strnlen(obj->name, 20));
}

