/**
  * @brief CAUTION: do not change this file - it is autogenerated.
  */

#include "car.h"
#include <common/xroad_aux.h>

typedef struct
{
   uint16_t block_length;
   uint16_t template_id;
   uint16_t schema_id;
   uint16_t version;
} message_header_t;

typedef struct
{
   uint16_t length;
   char data[];
} var_string_t;

typedef struct
{
   uint16_t block_length;
   uint16_t num_in_group;
} group_size_encoding_t;

typedef struct
{
   car_templates_t tid;
   char* data;
   size_t len;
   car_logger_cback_t cback;
   size_t var_offset;
} encoder_t;

struct car_group_encoder_s
{
   void* encoder;
   uint16_t idx;
   char* data;
};

typedef struct car_group_encoder_s car_group_encoder_t;

struct car_default_encoder_s
{
   encoder_t* base;
};

// types

// groups
// messages
typedef struct
{
   int32_t id[1];
   char name[20];
} car_t;

